#!/bin/bash

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $ROOT/lxc-default.conf
source ${1:-$PWD/lxc.conf}

# Remove port-forwarding for the container's sshd
if [[ $PF_SSH_ENABLE == "true" ]]; then
    CONTAINER_IP=$(sudo lxc-info -n $CONTAINER -iH)
    sudo iptables -t nat -D POSTROUTING -j MASQUERADE
    sudo iptables -t nat -D PREROUTING \
        -p tcp --dport $PF_SSH_PORT -j DNAT \
        --to-destination $CONTAINER_IP:22
    sudo iptables -F
fi

# Stop
sudo lxc-stop -n $CONTAINER
